# Generated by Django 4.1.4 on 2023-10-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_birth_date_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'normal'), ('admin', 'admin'), ('staff', 'staff')], default='normal', max_length=10),
        ),
    ]
