# Generated by Django 4.1.4 on 2023-10-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_name_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProducerProfile',
        ),
    ]
