# Generated by Django 4.1.4 on 2023-11-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_producerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_completed',
        ),
    ]
