# Generated by Django 4.1.4 on 2023-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_candidate_code_user_city_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
